avoid newline, split longline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,9 +19,10 @@ jobs:
       #- run: rebar3 xref
     - run: |
         mkdir dialyzer
-        echo "" > dialyzer/error.log
+        echo -n "" > dialyzer/error.log
       if: matrix.otp != 24
     - run: rebar3 dialyzer
       if: matrix.otp == 24
     - run: |
-        [ ${{ matrix.otp }} = 24 ] && true || { cat dialyzer/error.log ; test ! -s dialyzer/error.log ; }
+        [ ${{ matrix.otp }} = 24 ] && true \
+          || { cat dialyzer/error.log ; test ! -s dialyzer/error.log ; }
