run only dialyzer test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,54 +17,11 @@ jobs:
     - uses: actions/checkout@v2
     - run: rebar3 compile
       #- run: rebar3 xref
-      #- run: rebar3 dialyzer
-    - run: rebar3 edoc
-      id: edoc
-
-    - name: Run tests
+    - run: |
+        mkdir dialyzer
+        echo "Something" > dialyzer/error.log
       if: matrix.otp != 24
-      id: ctstep19
-      run: rebar3 eunit -v
-    - name: Run tests (OTP 24)
+    - run: rebar3 dialyzer
       if: matrix.otp == 24
-      id: ctstep
-      run: rebar3 eunit -v
-
-    - name: result2
-      if: always()
-      run: |
-        echo 'repository: ${{ github.repository }}'
-        echo 'edoc outcome: ${{ steps.edoc.outcome }}'
-        echo 'ctstep19 outcome: ${{ steps.ctstep19.outcome }}'
-        echo 'ctstep24 outcome: ${{ steps.ctstep.outcome }}'
-      continue-on-error: true
-
-    - name: Upload edoc to GitHub Pages
-      if: always() && (steps.ctstep.outcome == 'failure') && (github.repository == 'badlop/cache_tab')
-      uses: peaceiris/actions-gh-pages@v3
-      with:
-        publish_dir: doc
-        destination_dir: edoc
-        publish_branch: ecil
-        keep_files: true
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-
-    - name: Upload edoc to GitHub Pages
-      if: always() && (steps.ctstep.outcome == 'failure')
-      run: |
-        echo 'repository: ${{ github.repository }}'
-
-    - name: Upload edoc to GitHub Pages
-      if: always() && steps.ctstep.outcome == 'failure'
-      run: |
-        echo 'repository: ${{ github.repository }}'
-
-    - name: Upload edoc to GitHub Pages
-      if: always() && ${{ steps.ctstep.outcome }} == 'failure'
-      run: |
-        echo 'repository: ${{ github.repository }}'
-
-    - name: View links to Github Pages
-      if: always() && (steps.ctstep.outcome != 'success') && (github.repository == 'badlop/cache_tab')
-      run: |
-        echo "::notice::View this EDoc: https://badlop.github.io/cache_tab/"
+    - run: |
+        [[ ${{ matrix.otp }} = 24 ]] && true || { cat dialyzer/error.log ; test ! -s dialyzer/error.log }
